-- File:        ui_mm_spawn_dialog.script
-- Description: Spawn Dialog for STALKER CoP: Misery 2.0
-- Created:     2013/08/03
-- Last edit:	2013/08/10
-- Author:      Rowan Lewis [Measly Twerp] (rl@nbsp.io)
-- Version:     1.1

local knives = {
	"wpn_knife",
	"wpn_knife_inv_2",
	"wpn_knife_inv_3",
	"wpn_knife_inv_4",
	"wpn_knife_inv_5",
	"wpn_knife_m",
--	"wpn_knife_inv",					-- A duplicate of `wpn_knife`.
}

local pistols = {
	"wpn_beretta",
	"wpn_beretta_alt",
	"wpn_beretta_camo",
	"wpn_beretta_custom",
	"wpn_beretta_worn",
	"wpn_colt1911",
	"wpn_colt1911_alt1",
	"wpn_colt1911_alt2",
	"wpn_colt1911_camo",
	"wpn_colt1911_worn",
	"wpn_desert_eagle",
	"wpn_desert_eagle_alt",
	"wpn_desert_eagle_camo",
	"wpn_desert_eagle_custom",
	"wpn_desert_eagle_nimble",
	"wpn_desert_eagle_worn",
	"wpn_fort",
	"wpn_fort_camo",
	"wpn_fort_custom",
	"wpn_fort_rusty",
	"wpn_fort_worn",
	"wpn_gp100",
	"wpn_gsh18",
	"wpn_hpsa",
	"wpn_hpsa_alt",
	"wpn_hpsa_camo",
	"wpn_hpsa_custom",
	"wpn_hpsa_worn",
	"wpn_oc33",
	"wpn_pb",
	"wpn_personal_1",
	"wpn_pm",
	"wpn_pm_actor",
	"wpn_pm_alt",
	"wpn_pm_custom",
	"wpn_pm_worn",
	"wpn_sig220",
	"wpn_sig220_camo",
	"wpn_sig220_custom",
	"wpn_sig220_nimble",
	"wpn_sig220_rusty",
	"wpn_sig220_worn",
	"wpn_tt33",
	"wpn_usp",
	"wpn_usp_alt1",
	"wpn_usp_alt2",
	"wpn_usp_custom",
	"wpn_usp_worn",
	"wpn_walther",
	"wpn_walther_alt1",
	"wpn_walther_alt2",
	"wpn_walther_custom",
	"wpn_walther_worn",
}

local shotguns = {
	"wpn_bm16",
	"wpn_bm16_full",
	"wpn_bm16_gold",
	"wpn_bm16_rusty",
	"wpn_bm16_silver",
	"wpn_bm16_worn",
	"wpn_mossberg",
	"wpn_obrez",
	"wpn_protecta",
	"wpn_protecta_camo",
	"wpn_protecta_custom",
	"wpn_protecta_nimble",
	"wpn_protecta_worn",
	"wpn_saiga",
	"wpn_spas12",
	"wpn_spas12_alt",
	"wpn_spas12_custom",
	"wpn_spas12_nimble",
	"wpn_spas12_worn",
	"wpn_toz34",
	"wpn_toz34_alt",
	"wpn_toz34_decor",
	"wpn_toz34_new",
	"wpn_toz34_worn",
	"wpn_wincheaster1300",
	"wpn_wincheaster1300_alt",
	"wpn_wincheaster1300_camo",
	"wpn_wincheaster1300_rusty",
	"wpn_wincheaster1300_trapper",
	"wpn_wincheaster1300_worn",
}

local assault_rifles = {
	"wpn_abakan",
	"wpn_abakan_alt",
	"wpn_abakan_camo",
	"wpn_abakan_custom",
	"wpn_abakan_rusty",
	"wpn_abakan_worn",
	"wpn_aek973",
	"wpn_ak105",
	"wpn_ak47m",
	"wpn_ak47m_alt",
	"wpn_ak47m_camo",
	"wpn_ak47m_custom",
	"wpn_ak47m_modern",
	"wpn_ak47m_worn",
	"wpn_ak74",
	"wpn_ak74_alt",
	"wpn_ak74_camo",
	"wpn_ak74_custom1",
	"wpn_ak74_custom2",
	"wpn_ak74_rusty",
	"wpn_ak74_worn",
	"wpn_ak74u",
	"wpn_ak74u_camo",
	"wpn_ak74u_custom",
	"wpn_ak74u_rusty",
	"wpn_ak74u_snag",
	"wpn_ak74u_worn",
	"wpn_aks74_cobra",
	"wpn_aps",
	"wpn_famas3",
	"wpn_far15",
	"wpn_fn2000",
	"wpn_fn2000_alt1",
	"wpn_fn2000_alt2",
	"wpn_fn2000_alt3",
	"wpn_fn2000_custom",
	"wpn_fn2000_nimble",
	"wpn_fn2000_worn",
	"wpn_fnfal",
	"wpn_fnfallelcan",
	"wpn_fr2000",
	"wpn_g36",
	"wpn_g36_custom",
	"wpn_g36_nimble",
	"wpn_g43",
	"wpn_galil",
	"wpn_groza",
	"wpn_groza_nimble",
	"wpn_k98",
	"wpn_l85",
	"wpn_l85_camo",
	"wpn_l85_custom",
	"wpn_l85_worn",
	"wpn_lr300",
	"wpn_lr300_alt",
	"wpn_lr300_camo",
	"wpn_lr300_custom",
	"wpn_lr300_worn",
	"wpn_m16a1",
	"wpn_m1891",
	"wpn_m1891_alt",
	"wpn_m1891_alun",
	"wpn_m4a1",
	"wpn_mp5",
	"wpn_mp5_alt",
	"wpn_mp5_custom",
	"wpn_mp5_nimble",
	"wpn_mp5_worn",
	"wpn_ppsh41",
	"wpn_ppsh41_rednew",
	"wpn_ppsh41_redworn",
	"wpn_ppsh41_woodnew",
	"wpn_ppsh41_woodworn",
	"wpn_rpk74",
	"wpn_scorpion",
	"wpn_sig550",
	"wpn_sig550_alt",
	"wpn_sig550_custom",
	"wpn_sig550_luckygun",
	"wpn_sig550_sniper",
	"wpn_sig550_worn",
	"wpn_sig552",
	"wpn_sks",
	"wpn_sks_modern",
	"wpn_stg44",
	"wpn_stg44_alt",
	"wpn_stg44_new",
	"wpn_stg44_old",
	"wpn_stg44_worn",
	"wpn_ump45",
	"wpn_val",
	"wpn_vsk94",
	"wpn_xm8",
--	"wpn_aug",						-- Disabled because it causes a crash.
--	"wpn_sako",						-- Does not appear to be complete.
}

local sniper_rifles = {
	"pri_a17_gauss_rifle",
	"wpn_gauss",
	"wpn_m21",
	"wpn_m24",
	"wpn_sig550_sniper",
	"wpn_svd",
	"wpn_svd_nimble",
	"wpn_svu",
	"wpn_svu_nimble",
	"wpn_trg",
	"wpn_vintorez",
	"wpn_vintorez_ap",
	"wpn_vintorez_nimble",
	"wpn_ksvk",							-- Added in Misery 2.0.1
}

local heavy_weapons = {
	"wpn_pkm",
	"wpn_pkm_zulus",
	"wpn_rg-6",
	"wpn_rpg7",
}

local explosives = {
	"explo_balon_gas",
	"explo_jerrycan_fuel",
	"explo_metalcan_powder",
	"grenade_f1",
	"grenade_gd-05",
	"grenade_rgd5",
	"ied",
	"ied_blow",
	"ied_rpg",
	"mine",
--	"mine_blow",						-- Doesn't actually do anything.
--	"rpg_blow",							-- Doesn't actually do anything.
}

local ammunition = {
	"ammo_11.43x23_ap",
	"ammo_11.43x23_fmj",
	"ammo_11.43x23_hydro",
	"ammo_12x70_buck",
	"ammo_12x76_zhekan",
	"ammo_12x76_zhekan_heli",
	"ammo_12.7x108_ap",
	"ammo_357_hp_mag",
	"ammo_357_hp_mag_ap",
	"ammo_5.45x39_ap",
	"ammo_5.45x39_fmj",
	"ammo_5.56x45_ap",
	"ammo_5.56x45_ss190",
	"ammo_7.62x39_ap",
	"ammo_7.62x39_fmj",
	"ammo_7.62x51_ap",
	"ammo_7.62x51_fmj",
	"ammo_7.62x54_7h1",
	"ammo_7.62x54_7h14",
	"ammo_7.62x54_ap",
	"ammo_7.92x33_ap",
	"ammo_7.92x33_fmj",
	"ammo_9x18_ap",
	"ammo_9x18_fmj",
	"ammo_9x18_pmm",
	"ammo_9x19_ap",
	"ammo_9x19_fmj",
	"ammo_9x19_pbp",
	"ammo_9x39_ap",
	"ammo_9x39_pab9",
	"ammo_gauss",
	"ammo_gauss_cardan",
	"ammo_m209",
	"ammo_magnum_300",
	"ammo_magnum_300_ap",
	"ammo_og-7b",
	"ammo_pkm_100",
	"ammo_vog-25",
}

local attachments = {
	"wpn_addon_grenade_launcher",
	"wpn_addon_grenade_launcher_m203",
	"wpn_addon_scope",
	"wpn_addon_scope_acog",
	"wpn_addon_scope_acog_night",
	"wpn_addon_scope_acog_trijicon",
	"wpn_addon_scope_detector",
	"wpn_addon_scope_m24",
	"wpn_addon_scope_moist",
	"wpn_addon_scope_night",
	"wpn_addon_scope_susat",
	"wpn_addon_scope_susat_custom",
	"wpn_addon_scope_susat_dusk",
	"wpn_addon_scope_susat_moist",
	"wpn_addon_scope_susat_night",
	"wpn_addon_scope_susat_worn",
	"wpn_addon_scope_susat_x1.6",
	"wpn_addon_scope_vsk",
	"wpn_addon_scope_worn",
	"wpn_addon_scope_ww2",
	"wpn_addon_scope_ww2_moist",
	"wpn_addon_scope_ww2_worn",
	"wpn_addon_scope_x2.7",
	"wpn_addon_scope_zf4",
	"wpn_addon_scope_zf4_moist",
	"wpn_addon_scope_zf4_worn",
	"wpn_addon_silencer",
	"wpn_addon_silencer_1143x23",
	"wpn_addon_silencer_545x39",
	"wpn_addon_silencer_556x45",
	"wpn_addon_silencer_762x39",
	"wpn_addon_silencer_762x51",
	"wpn_addon_silencer_762x54",
	"wpn_addon_silencer_9x18",
	"wpn_addon_silencer_9x19",
	"wpn_addon_silencer_9x39",
--	"wpn_addon_scope_pu9130",			-- Disabled as it is marked TODO.
--	"wpn_addon_scope_zf9",				-- Disabled as it is marked TODO.
}

local outfits = {
	"coat_heavy_outfit",
	"coat_outfit",
	"cs_heavy_outfit",
	"dolg_heavy_outfit",
	"dolg_outfit",
	"ecologist_green_outfit",
	"exo_outfit",
	"helm_battle",
	"helm_cloth_mask",
	"helm_hardhat",
	"helm_hardhat_snag",
	"helm_protective",
	"helm_respirator",
	"helm_respirator_heavy",
	"helm_respirator_joker",
	"helm_tactic",
	"military_outfit",
	"novice_outfit",
	"scientific_outfit",
	"specops_outfit",
	"stalker_outfit",
	"stalker_outfit_barge",
	"svoboda_heavy_outfit",
	"svoboda_light_outfit",
--	"ecologist_suit_red_suit",			-- Disabled because it causes a crash.
--	"helmet",							-- Shows up as 'st_helmet' worthless?
}

local equipment = {
	"af_aac",
	"af_aam",
	"af_camelbak",
	"af_cooler",
	"af_frames",
	"af_freon",
	"af_grid",
	"af_iam",
	"af_kevlar",
	"af_plates",
	"af_surge",
	"ammo_bad",
	"army_patch",
	"bandit_patch",
	"batteries",
	"batteries_ccell",
	"batteries_dead",
	"batteries_empty",
	"beadspread",
	"book1",
	"book2",
	"book3",
	"boots",
	"cards",
	"cooking",
	"crowbar",
	"csky_patch",
	"cutlery",
	"detector_advanced",
	"detector_elite",
	"detector_scientific",
	"detector_simple",
	"device_flashlight",
	"device_torch",
	"dolg_patch",
	"drugs_kit",
	"fieldcooker",
	"freedom_patch",
	"geiger_dead",
	"grooming",
	"guitar_a",
	"hammer_inv",
	"harmonica_a",
	"headlamp",
	"itm_backpack",
	"jar",
	"jewelry_box",
	"journal",
	"kit_hunt",
	"maps_kit",
	"meinkampf",
	"merc_patch",
	"mili_maps",
	"mirror",
	"monolith_patch",
	"picture_woman",
	"porn",
	"porn2",
	"radio",
	"radio2",
	"renegade_patch",
	"repair_kit",
	"rope",
	"roubles",
	"shovel_mili",
	"shovel_old",
	"sleep_bag",
	"spareparts",
	"stalker_patch",
	"survivalguide",
	"swiss",
	"synthrope",
	"tarpaulin",
	"test_flashlight",
	"underwear",
	"walkie",
	"welding_goggles",
	"wpn_binoc",
	"wpn_upd",
--	"compression_bag",					-- Inflatable bed! Neat, but useless.
--	"device_identity_card",				-- A waste of space, and useless.
--	"device_torch_dummy",				-- A duplicate of `device_torch`.
--	"flashlight_broken",				-- A duplicate of `device_flashlight`.
--	"flashlight_old",					-- A duplicate of `device_flashlight`.
--	"identity_card_assaulter",			-- A waste of space, and useless.
--	"identity_card_recon",				-- A waste of space, and useless.
--	"identity_card_sniper",				-- A waste of space, and useless.
--	"wpn_binoc_inv",					-- A duplicate of `wpn_binoc`.
}

local artefacts = {
	"af_baloon",
	"af_blood",
	"af_compass",
	"af_cristall",
	"af_cristall_flower",
	"af_dummy_battery",
	"af_dummy_dummy",
	"af_dummy_glassbeads",
	"af_electra_flash",
	"af_electra_moonlight",
	"af_electra_sparkler",
	"af_eye",
	"af_fire",
	"af_fireball",
	"af_fuzz_kolobok",
	"af_glass",
	"af_gold_fish",
	"af_gravi",
	"af_ice",
	"af_medusa",
	"af_mincer_meat",
	"af_night_star",
	"af_oasis_heart",
	"af_quest_b14_twisted",
	"af_soul",
	"af_vyvert",
	"jup_b1_half_artifact",
}

local disposables = {
	"adrenalin",
	"akvatab",
	"antirad",
	"bandage",
	"beans",
	"beer",
	"bottle_metal",
	"bread",
	"breadold",
	"caffeine",
	"chili",
	"chocolate",
	"cigar",
	"cigar1",
	"cigar2",
	"cigar3",
	"cigarettes",
	"cigarettes_lucky",
	"cigarettes_russian",
	"cocaine",
	"conserva",
	"corn",
	"drug_anabiotic",
	"drug_antidot",
	"drug_booster",
	"drug_coagulant",
	"drug_psy_blockade",
	"drug_radioprotector",
	"drug_sleepingpills",
	"energy_drink",
	"flask",
	"glucose",
	"glucose_s",
	"hand_rolling_tobacco",
	"joint",
	"kolbasa",
	"marijuana",
	"meat_bloodsucker",
	"meat_boar",
	"meat_chimera",
	"meat_dog",
	"meat_flesh",
	"meat_pseudodog",
	"meat_snork",
	"meat_tushkano",
	"medkit",
	"medkit_army",
	"medkit_scientic",
	"mineral_water",
	"mint",
	"morphine",
	"mre",
	"mre2",
	"mre3",
	"nuts",
	"protein",
	"raisins",
	"ration_ru",
	"ration_ru2",
	"ration_ru3",
	"ration_ru4",
	"ration_ru5",
	"ration_ru6",
	"ration_ru7",
	"ration_ukr",
	"ration_ukr2",
	"ration_ukr3",
	"ration_ukr4",
	"ration_ukr5",
	"ration_ukr6",
	"rebirth",
	"salicidic_acid",
	"salmon",
	"sausage",
	"stimpack",
	"stimpack_army",
	"stimpack_scientic",
	"survival_kit",
	"tea",
	"tetanus",
	"tomato",
	"tushonka",
	"vodka",
	"vodka2",
	"vodka_quality",
	"water_drink",
--	"drink_crow",						-- Appears to be incomplete.
--	"medkit_script",					-- A duplicate of `medkit`.
}

local quest_items = {
	"device_flash_snag",
	"device_pda_port_bandit_leader",
	"device_pda_zat_b5_dealer",
	"jup_a9_conservation_info",
	"jup_a9_delivery_info",
	"jup_a9_evacuation_info",
	"jup_a9_losses_info",
	"jup_a9_meeting_info",
	"jup_a9_power_info",
	"jup_a9_way_info",
	"jup_b10_notes_01",
	"jup_b10_notes_02",
	"jup_b10_notes_03",
	"jup_b10_ufo_memory",
	"jup_b10_ufo_memory_2",
	"jup_b200_tech_materials_acetone",
	"jup_b200_tech_materials_capacitor",
	"jup_b200_tech_materials_textolite",
	"jup_b200_tech_materials_transistor",
	"jup_b200_tech_materials_wire",
	"jup_b202_bandit_pda",
	"jup_b205_sokolov_note",
	"jup_b206_plant",
	"jup_b207_merc_pda_with_contract",
	"jup_b209_monster_scanner",
	"jup_b32_scanner_device",
	"jup_b46_duty_founder_pda",
	"jup_b47_jupiter_products_info",
	"jup_b47_merc_pda",
	"jup_b9_blackbox",
	"lx8_service_instruction",
	"pri_a19_american_experiment_info",
	"pri_a19_lab_x10_info",
	"pri_a19_lab_x16_info",
	"pri_a19_lab_x18_info",
	"pri_a19_lab_x7_info",
	"pri_a25_explosive_charge_item",
	"pri_b306_envoy_pda",
	"pri_b35_lab_x8_key",
	"pri_b36_monolith_hiding_place_pda",
	"toolkit_1",
	"toolkit_2",
	"toolkit_3",
	"zat_a23_access_card",
	"zat_a23_gauss_rifle_docs",
	"zat_a23_labx8_key",
	"zat_b12_documents_1",
	"zat_b12_documents_2",
	"zat_b12_key_1",
	"zat_b12_key_2",
	"zat_b20_noah_pda",
	"zat_b22_medic_pda",
	"zat_b33_safe_container",
	"zat_b39_joker_pda",
	"zat_b40_notebook",
	"zat_b40_pda_1",
	"zat_b40_pda_2",
	"zat_b44_barge_pda",
	"zat_b57_gas",
}

local non_player_characters = {
	{"flesh_normal",						"Flesh"},
	{"flesh_strong",						"Flesh (Strong)"},

	{"bloodsucker_normal",					"Bloodsucker"},
	{"bloodsucker_weak",					"Bloodsucker (Weak)"},
	{"bloodsucker_strong",					"Bloodsucker (Strong)"},

	{"dog_normal",							"Dog"},
	{"dog_weak",							"Dog (Weak)"},
	{"dog_strong",							"Dog (Strong)"},
	{"dog_cute",							"Dog (Cute)"},

	{"boar_normal",							"Boar"},
	{"boar_strong",							"Boar (Strong)"},

	{"pseudodog_normal",					"Pseudodog"},

	{"psy_dog_normal",						"PsyDog"},
	{"psy_dog_phantom",						"Psydog (Phantom)"},

	{"gigant_normal",						"Pseudogiant"},

	{"m_controller_normal",					"Controller"},
	{"controller_tubeman",					"Controller (Tubeman)"},
	{"controller_fake",						"Controller (Fake)"},

	{"m_poltergeist_normal_flame",			"Poltergeist (Flame)"},
	{"m_poltergeist_normal_tele",			"Poltergeist (Tele)"},
	{"labx8_poltergeist",					"Poltergeist (Lab X8)"},
	{"poltergeist_fake",					"Poltergeist (Fake)"},
	"pri_a25_poltergeist",

	{"snork_normal",						"Snork"},
	{"snork_weak",							"Snork (Weak)"},
	{"snork_strong",						"Snork (Strong)"},
	{"snork_indoor",						"Snork (Indoors)"},
	{"snork_outdoor",						"Snork (Outdoors)"},

	{"tushkano_normal",						"Rat"},

	{"chimera_normal",						"Chimera"},

	{"burer_normal",						"Burer"},

	"zombie_1_ghost",
	"zombie_1_ghost",
	"zombie_2_ghost",
	"zombie_3_ghost",
	"zombie_1",
	"zombie_2",
	"zombie_3",
	"zombie_trup_1",
	"zombie_trup_2",

	{"fracture_normal",						"Fracture"},
	{"fracture_weak",						"Fracture (Weak)"},
	{"fracture_strong",						"Fracture (Strong)"},

	{"cat_normal",							"Cat"},
	{"cat_weak",							"Cat (Weak)"},
	{"cat_strong",							"Cat (Strong)"},

	{"sci_1",								"Scientist 1"},
	{"sci_2",								"Scientist 2"},
	{"sci_3",								"Scientist 3"},

	{"sim_default_duty_0",					"Duty (Beginner)"},
	{"sim_default_duty_1",					"Duty (Stalker)"},
	{"sim_default_duty_2",					"Duty (Pro)"},
	{"sim_default_duty_3",					"Duty (Veteran)"},
	{"sim_default_duty_4",					"Duty (Master)"},
	"sim_default_duty_hunter_day_1",
	"sim_default_duty_hunter_day_2",
	"sim_default_duty_hunter_night",
	"sim_default_duty_commando_sniper",
	"sim_default_duty_commando_1",
	"sim_default_duty_commando_2",

	{"sim_default_monolith_0",				"Monolith (Beginner)"},
	{"sim_default_monolith_1",				"Monolith (Stalker)"},
	{"sim_default_monolith_2",				"Monolith (Pro)"},
	{"sim_default_monolith_3",				"Monolith (Veteran)"},
	{"sim_default_monolith_4",				"Monolith (Master)"},
	"sim_default_monolith_sci_1",
	"sim_default_monolith_sci_2",

	{"sim_default_freedom_0",				"Freedom (Beginner)"},
	{"sim_default_freedom_1",				"Freedom (Stalker)"},
	{"sim_default_freedom_2",				"Freedom (Pro)"},
	{"sim_default_freedom_3",				"Freedom (Veteran)"},
	{"sim_default_freedom_4",				"Freedom (Master)"},
	"sim_default_freedom_sci_1",
	"sim_default_freedom_sci_2",

	{"sim_default_bandit_0",				"Bandit (Beginner)"},
	{"sim_default_bandit_1",				"Bandit (Stalker)"},
	{"sim_default_bandit_2",				"Bandit (Pro)"},
	{"sim_default_bandit_3",				"Bandit (Veteran)"},
	{"sim_default_bandit_4",				"Bandit (Master)"},

	{"sim_default_stalker_0",				"Stalker (Beginner)"},
	{"sim_default_stalker_1",				"Stalker (Stalker)"},
	{"sim_default_stalker_2",				"Stalker (Pro)"},
	{"sim_default_stalker_3",				"Stalker (Veteran)"},
	{"sim_default_stalker_4",				"Stalker (Master)"},
	"sim_default_stalker_sci_1",
	"sim_default_stalker_sci_2",
	"sim_default_stalker_hunter_day",
	"sim_default_stalker_hunter_night",
	"sim_default_stalker_guide",

	{"sim_default_military_0",				"Military (Beginner)"},
	{"sim_default_military_1",				"Military (Stalker)"},
	{"sim_default_military_2",				"Military (Pro)"},
	{"sim_default_military_3",				"Military (Veteran)"},
	{"sim_default_military_3_sniper",		"Military (Sniper)"},
	{"sim_default_military_4",				"Military (Master)"},

	{"sim_default_killer_0",				"Merc (Beginner)"},
	{"sim_default_killer_1",				"Merc (Stalker)"},
	{"sim_default_killer_2",				"Merc (Pro)"},
	{"sim_default_killer_3",				"Merc (Veteran)"},
	{"sim_default_killer_4",				"Merc (Master)"},

	{"sim_default_zombied_1",				"Zombified (Stalker)"},
	{"sim_default_zombied_2",				"Zombified (Pro)"},
	{"sim_default_zombied_3",				"Zombified (Veteran)"},
	{"sim_default_zombied_4",				"Zombified (Master)"},

	"zat_stalker_medic",

	"zat_b106_stalker_gonta",
	"zat_b14_stalker_1",
	"zat_b14_stalker_2",
	"zat_b14_stalker_3",
	"zat_b38_stalker_cop",
	"zat_b38_stalker_corpse_1",
	"zat_b38_stalker_corpse_2",
	"zat_b38_stalker_corpse_3",
	"zat_b38_stalker_cop_dead",
	"zat_b38_stalker_hunter",
	"zat_b30_owl_stalker_trader",
	"zat_b7_duty_illicit_dealer",
	"zat_b5_stalker_raider_1",
	"zat_b5_stalker_raider_2",
	"zat_b5_stalker_raider_3",
	"zat_b5_stalker_raider_4",
	"zat_b5_stalker_raider_leader",
	"zat_b7_bandit_boss_dead",
	"zat_b5_stalker_commander",
	"zat_b5_stalker_commander_b7",
	"zat_b5_stalker_1",
	"zat_b5_stalker_2",
	"zat_b5_stalker_3",
	"zat_b5_stalker_4",
	"zat_b5_dealer_assistant_1",
	"zat_b5_dealer_assistant_2",
	"zat_b7_bandit_boss_sultan",

	{"zat_b18_noah",						"Noah"},

	"pri_a17_military_captain_tarasov",
	"pri_a17_military_prapor_valentyr",
	"pri_a17_military_sergeant_morozov",
	"pri_a17_military_lieutenant_podorojniy",
	"pri_a17_monolith_preacher",
	"pri_a17_military_colonel_kovalski",

	"pri_a15_military_recon_leader",
	"pri_a15_military_recon_1",
	"pri_a15_military_recon_2",
	"pri_a15_military_recon_3",

	"jup_b218_vano_in_suit",
	"pri_a15_sokolov",
	"pri_a15_sokolov_sci",
	"pri_a15_sokolov_sci_head",
	"pri_a22_military_merkulov",
	"pri_a22_military_skelja",

	"pri_a21_sentry_lieutenant_stecenko",

	"jup_a12_stalker_assaulter",
	"jup_a12_stalker_diplomat",
	"jup_a12_stalker_prisoner",
	"jup_a12_bandit_chief",
	"jup_a12_bandit_guard",
	"jup_a12_bandit_cashier",
	"jup_a12_merc_cover",

	"jup_b207_merc_illicit_dealer",
	"jup_b207_merc_leader",
	"jup_b207_duty_security_squad_leader",
	"jup_b207_freedom_recon_squad_leader",
	"jup_b207_freedom_assault_squad_leader",

	"jup_a10_bandit_leader",
	"jup_a10_stalker_vano",

	"jup_b6_scientist_biochemist",
	"jup_b6_scientist_nuclear_physicist",

	"jup_b9_shliachin",

	"jup_b217_stalker_tech",

	"jup_b10_stalker_drunk",

	"jup_b10_stalker_drunk_dead",

	"jup_b220_trapper",

	"jup_b4_monolith_squad_leader_monolith_skin",

	"jup_b4_monolith_squad_leader_duty_skin",

	"jup_b4_monolith_squad_leader_freedom_skin",

	"jup_b4_monolith_squad_leader_freedom_mon_skin",

	"jup_b4_monolith_squad_leader_duty_mon_skin",

	"jup_b4_monolith_squad_soldier_1_monolith_skin",

	"jup_b4_monolith_squad_soldier_1_duty_skin",

	"jup_b4_monolith_squad_soldier_1_freedom_skin",

	"jup_b4_monolith_squad_soldier_2_monolith_skin",

	"jup_b4_monolith_squad_soldier_2_duty_skin",

	"jup_b4_monolith_squad_soldier_2_freedom_skin",

	"jup_b4_monolith_squad_soldier_3_monolith_skin",

	"jup_b4_monolith_squad_soldier_3_duty_skin",

	"jup_b4_monolith_squad_soldier_3_freedom_skin",

	"jup_b4_monolith_squad_soldier_4_monolith_skin",

	"jup_b4_monolith_squad_soldier_4_duty_skin",

	"jup_b4_monolith_squad_soldier_4_freedom_skin",

	"jup_b4_monolith_squad_soldier_5_monolith_skin",

	"jup_b4_monolith_squad_soldier_5_duty_skin",

	"jup_b4_monolith_squad_soldier_5_freedom_skin",

	"jup_b4_freedom_help",

	"jup_b4_duty_help",

	"jup_b4_freedom_leader",

	"jup_b4_duty_leader",

	"jup_b6_scientist_tech",
	"jup_b1_stalker_1",
	"jup_b1_stalker_2",
	"jup_b1_stalker_3",
	"jup_b1_stalker_4",
	"jup_b1_pro_stalker_1",
	"jup_b1_pro_stalker_2",
	"jup_b1_pro_stalker_3",
	"jup_b1_pro_stalker_4",

	"jup_b6_freedom_stalker_1",
	"jup_b6_freedom_stalker_2",
	"jup_b6_freedom_stalker_3",
	"jup_b6_freedom_stalker_4",

	"jup_b6_duty_stalker_1",
	"jup_b6_duty_stalker_2",
	"jup_b6_duty_stalker_3",
	"jup_b6_duty_stalker_4",

	"jup_b6_stalker_prisoner",
	"jup_b6_stalker_assaulter",
	"jup_b6_stalker_diplomat",

	"jup_b6_stalker_gonta",
	"jup_b6_stalker_garmata",
	"jup_b6_stalker_crab",

	"zat_a2_stalker_barmen",
	"zat_a2_stalker_mechanic",
	"zat_a2_stalker_nimble",

	"zat_b22_stalker_medic",

	"jup_b25_stalker_senya",
	"jup_b25_freedom_flint",

	"zat_b103_lost_merc_leader",
	"zat_b103_lost_merc_1",
	"zat_b103_lost_merc_2",
	"zat_b103_lost_merc_3",
	"zat_b103_lost_merc_4",
	"zat_b103_lost_merc_5",
	"zat_b103_lost_merc_6",
	"zat_b103_lost_merc_7",

	"zat_b7_stalker_raider_leader",
	"zat_b7_stalker_raider_1",
	"zat_b7_stalker_raider_2",
	"zat_b7_stalker_raider_3",
	"zat_b7_stalker_victim_1",

	"zat_b33_stalker_snag",
	"zat_b28_draper",
	"zat_b28_umerov",
	"zat_b28_smoliak",

	"zat_b100_military_1",
	"zat_b100_military_2",
	"zat_b100_military_3",

	"zat_b42_mayron",

	"zat_b29_stalker_rival_1",
	"zat_b29_stalker_rival_2",
	"zat_b29_stalker_rival_default_1",
	"zat_b29_stalker_rival_default_2",

	"zat_b52_port_bandit_leader",

	"jup_a6_stalker_medik",
	"jup_b15_zulus",
	"jup_b202_stalker_snag",
	"jup_a6_stalker_barmen",
	"jup_b202_bandit",

	"jup_b19_freedom_yar",
	"jup_b19_merc_1",
	"jup_b19_merc_2",
	"jup_b19_merc_3",
	"jup_b19_merc_4",
	"jup_b19_merc_5",

	"jup_b43_stalker_assistant",

	"zat_b215_stalker_guide",

	"pri_a25_army_medic",

	"pri_a15_actor",
	"pri_a15_vano",
	"pri_a15_sokolov_scene",
	"pri_a15_zulus",
	"pri_a15_wanderer",
	"pri_a15_military_tarasov",
	"pri_a15_military_2",
	"pri_a15_military_3",
	"pri_a15_military_4",

	"pri_a22_army_signaller",
	"pri_b35_merc_leader",
	"pri_b35_merc_grenade_launcher_1",
	"pri_b35_merc_grenade_launcher_2",
	"pri_b35_envoy",
	"pri_b35_guard_envoy_1",
	"pri_b35_guard_envoy_2",

	"pri_b306_envoy",

	"jup_b46_duty_founder",
	"jup_b46_duty_founder_squad_01",
	"jup_b46_duty_founder_squad_02",
	"jup_b46_duty_founder_squad_03",
	"jup_b46_duty_founder_squad_04",
	"jup_a6_freedom_leader",
	"jup_a6_duty_leader",

	"zat_b40_merc_squad_leader_1",
	"zat_b40_merc_squad_leader_2",

	"zat_b20_noah_teleport",

	"zat_b44_stalker_barge",

	"pri_b36_monolith_sniper",
	"pri_b36_monolith_master_hiding_place",
	"pri_b36_monolith_marine_sniper",

	"zat_b53_artefact_hunter_1",
	"zat_b53_artefact_hunter_2",

	"pri_a22_military_yarmoshuk",

	"pri_b305_strelok",

	"pri_a28_evac_com",

	"zat_b106_stalker_garmata",
	"zat_b106_stalker_crab",

	"jup_b47_merc_01",
	"jup_b47_merc_02",
	"jup_b47_merc_03",
	"jup_b47_merc_04",
	"jup_b47_merc_05",
	"jup_b47_merc_06",
	"jup_b47_merc_07",

	"jup_b219_stalker_tech",
	"jup_b219_monolith_squad_leader_freedom_skin",
	"jup_b219_vano",
	"jup_b219_soldier",
	"jup_b219_zulus",

	"pas_b400_vano",
	"pas_b400_sokolov",
	"pas_b400_zulus",
	"pas_b400_wanderer",
	"pas_b400_monolith_sniper",

	"sim_default_stalker_pri_a16",
}

local weather_effects = {
	{"af3_bright_clear_0",					"Clear"},
	{"af3_bright_cloudy",					"Cloudy"},
	{"af3_bright_foggy",					"Foggy"},
	{"af3_bright_partly_0",					"Partly cloudy"},
	{"af3_bright_rain",						"Rainy"},
	{"af3_bright_storm",					"Stormy"},
	{"af3_bright_veryfoggy",				"Very foggy"},
}

local categories = {
	all =									'All Items',
	knives =								'Knives',
	pistols =								'Pistols',
	shotguns =								'Shotguns',
	assault_rifles =						'Assault Rifles',
	sniper_rifles =							'Sniper Rifles',
	heavy_weapons =							'Heavy Weapons',
	ammunition =							'Ammunition',
	explosives =							'Explosives',
	attachments =							'Attachments',
	artefacts =								'Artefacts',
	outfits =								'Outfits',
	equipment =								'Equipment',
	disposables =							'Disposables',
	quest_items =							'Quest Items',
	non_player_characters =					'Non Player Characters',
	weather_effects =						'Weather Effects',
}

local status = {
	category =								categories.all,
	npc_distance =							1,
}

class "list_item" (CUIListBoxItem)

function list_item:__init(size) super(size.y)
	self:SetTextColor(GetARGB(255, 170, 170, 170))
	self:SetWndSize(size)

	self.nice = self:GetTextItem()
	self.nice:SetFont(GetFontLetterica18Russian())
	self.nice:SetEllipsis(true)
	self.nice:SetWndPos(vector2():set(0, 0))
	self.nice:SetWndSize(vector2():set(size.x * 0.6, size.y))

	self.name = self:AddTextField('', size.x * 0.4)
	self.name:SetFont(GetFontLetterica16Russian())
	self.name:SetEllipsis(true)
	self.name:SetWndPos(vector2():set(size.x * 0.6, 0))
	self.name:SetWndSize(vector2():set(size.x * 0.4, size.y))
end

function list_item:__finalize()
end

class "dialog" (CUIScriptWnd)

function dialog:__init() super()
	self:InitControls()
	self:InitCallBacks()
	self:InitData()
end

function dialog:__finalize()
end

function dialog:InitControls(x, y, xml, handler)
	self:SetWndRect(Frect():set(0, 0, 1024, 768))

	local xml = CScriptXmlInit()
	local ctrl

	xml:ParseFile('ui_mm_spawn_dialog.xml')
	xml:InitStatic('background', self)

	ctrl = CUIWindow()
	xml:InitWindow('spawn_item', 0, ctrl)
	self.spawn_item_size = vector2():set(ctrl:GetWidth(), ctrl:GetHeight())

	self.form = xml:InitStatic('form', self)
	xml:InitStatic('form:caption', self.form)


	-- Form -------------------------------------------------

	self.category_selector = xml:InitComboBox('form:category_selector', self)
	self:Register(self.category_selector, 'category_selector')

	xml:InitFrame('form:list_frame', self)
	self.list = xml:InitListBox('form:list', self)


	-- NPC spawning -----------------------------------------

	ctrl = xml:InitStatic('form:cap_distance', self)
	self:Register(ctrl, 'form:cap_distance')

	self.npc_distance = xml:InitEditBox('form:txt_distance', self)
	self:Register(self.npc_distance, 'txt_distance')
	self.npc_distance:SetText(tostring(status.npc_distance))


	-- Controls ---------------------------------------------

	self.list:ShowSelectedItem(true)
	self:Register(self.list, 'list_window')

	ctrl = xml:Init3tButton('form:btn_apply' ,self)
	self:Register(ctrl, 'btn_apply')

	ctrl = xml:Init3tButton('form:btn_cancel', self)
	self:Register(ctrl, 'btn_cancel')
end

function dialog:InitCallBacks()
	-- Controls ---------------------------------------------

	self:AddCallback(
		'category_selector',
		ui_events.LIST_ITEM_SELECT,
		self.OnCategoryItemSelect,
		self
	)

	self:AddCallback(
		'list_window',
		ui_events.WINDOW_LBUTTON_DB_CLICK,
		self.OnButtonApplyClicked,
		self
	)

    self:AddCallback(
    	'btn_apply',
    	ui_events.BUTTON_CLICKED,
    	self.OnButtonApplyClicked,
    	self
    )
	self:AddCallback(
		'btn_cancel',
		ui_events.BUTTON_CLICKED,
		self.OnButtonCancelClicked,
		self
	)
end

function dialog:InitData()
	self.data = {}
	self.categories = 1

	-- Add 'All Items' to combo box
	self.category_selector:AddItem(categories.all, self.categories)

	-- Build our data table
	self:AppendData(categories.knives, knives)
	self:AppendData(categories.pistols, pistols)
	self:AppendData(categories.shotguns, shotguns)
	self:AppendData(categories.assault_rifles, assault_rifles)
	self:AppendData(categories.sniper_rifles, sniper_rifles)
	self:AppendData(categories.heavy_weapons, heavy_weapons)
	self:AppendData(categories.ammunition, ammunition)
	self:AppendData(categories.explosives, explosives)
	self:AppendData(categories.attachments, attachments)
	self:AppendData(categories.artefacts, artefacts)
	self:AppendData(categories.outfits, outfits)
	self:AppendData(categories.equipment, equipment)
	self:AppendData(categories.disposables, disposables)
	self:AppendData(categories.quest_items, quest_items)
	self:AppendData(categories.non_player_characters, non_player_characters)
	self:AppendData(categories.weather_effects, weather_effects)

	-- Sort all of the added data
	table.sort(self.data, function(a, b) return a.sortable < b.sortable end)

	self:FillList(status.category)
end

function dialog:AppendData(category, data)
	self.categories = 1 + self.categories
	self.category_selector:AddItem(category, self.categories)

	for key, value in ipairs(data) do
		local item = {
			id =		value,
			name =		value,
			category =	category,
		}

		-- Custom translation provided:
		if type(value) == 'table' then
			item.id = value[1]
			item.name = value[2]
		end

		-- Attempt to get the name of the item as used in the inventory:
		if system_ini():section_exist(item.id) and system_ini():line_exist(item.id, 'inv_name') then
			item.name = system_ini():r_string(item.id, 'inv_name')
		end

		-- Translate the name (we hope):
		item.name = game.translate_string(item.name)

		-- Strip characters out to make sorting human friendly
		item.sortable = item.name:lower():gsub('%W+', ' '):gsub('^ +', ''):gsub(' +$', '')

		table.insert(self.data, item)
	end
end

function dialog:FillList(category)
	self.list:Clear()
	self.category_selector:SetText(category)
	status.category = category

	for i = 1, #self.data do
		if (category == categories.all) or (category == self.data[i].category) then
			local item = list_item(self.spawn_item_size)

			item.id = self.data[i].id
			item.category = self.data[i].category

			item.nice:SetText(self.data[i].name)
			item.name:SetText(self.data[i].id)

			self.list:AddExistingItem(item)
		end
	end
end

function dialog:OnCategoryItemSelect()
	self:FillList(self.category_selector:GetText())
end

function dialog:OnButtonApplyClicked()
	if self.list:GetSize() == 0 then
		return
	end

	local item = self.list:GetSelectedItem()

	if not(item) then
		return
	end

	-- Trigger weather effects/changes:
	if item.category == categories.weather_effects then
		level.set_weather(item.id, true)

	-- Spawn NPCs in front of the camera:
	elseif item.category == categories.non_player_characters then
		local position = db.actor:position()
		local direction = device().cam_dir
		local distance = tonumber(self.npc_distance:GetText())

		-- Keep what the user entered for next time
		status.npc_distance = distance

		-- Fixed range, for sanity
		if distance == nil or distance < 1 then
			distance = 1
		elseif distance > 500 then
			distance = 500
		end

		position.x = position.x + (distance * direction.x)
		position.y = position.y + (distance * direction.y)
		position.z = position.z + (distance * direction.z)

		alife():create(item.id, position, 0, 0)

	-- Spawn other items in the actors inventory:
	else
		local actor = db.actor:id()

		alife():create(item.id, db.actor:position(), 0, 0, actor)
	end
end

function dialog:OnButtonCancelClicked()
	self.owner:ShowDialog(true)
	self:HideDialog()
	self.owner:Show(true)
end

function dialog:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self, dik, keyboard_action)

	local bind = dik_to_bind(dik)

	if bind == key_bindings.kQUIT then
		self:OnButtonCancelClicked()

	elseif dik == 28 then
		self:OnButtonApplyClicked()
	end

	return true
end